spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/staemdb2
    username: postgres
    password: mariobrosluigi
    ##driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
